title: Diego Viana | Security Insights
description: Governança, IA e Defesa Cibernética
remote_theme: pages-themes/hacker@v0.2.0 # Um tema com visual "terminal", muito usado em segurança
plugins:
  - jekyll-remote-theme
  - jekyll-feed
