title: Diego Viana | Security Blog
description: Insights de Cybersecurity, Governan√ßa e IA.
theme: jekyll-theme-hacker
# O segredo para o 404 parar:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
